### ISSUE TITLE
SRAtoVCF.py -p flag

### ISSUE THREAD

**Issue by tatumdmortimer** [tracysmith/RGAPepPipe#21]
The -p flag starts the pipeline at a specific program for the first item in the input file, but runs the pipeline from the beginning for the rest. Can it be changed (or create a separate flag) to start the pipeline from a certain point for all of them? For example, I'd like to start the pipeline at the bwa step because I already have trimmed reads.

**Comment by mfossen** [comment]
Should be fixed and will always start at whatever program is chosen.
