### ISSUE TITLE
Starting pipeline in the middle automatically doesn't check read length

### ISSUE THREAD

**Issue by tatumdmortimer** [tracysmith/RGAPepPipe#22]
If the pipeline is started after fastqc is run, it doesn't check the read length and automatically uses the version of bwa for very short reads (most of our reads are longer). Could we move the code that checks the read length to a different spot or make bwa-mem the default algorithm?

**Comment by mfossen** [comment]
bwa-mem is the default for -p bwa now, use -p bwashort to use the other version. Modified trim_galore function as well to use bwa-mem by default if it's started using -p trim_galore.
