### ISSUE TITLE
GATK Depth of Coverage

### ISSUE THREAD

**Issue by ONeillMB1** [tracysmith/RGAPepPipe#5]
It appears the pipeline runs the GATK DepthOfCoverage tool but is never output anywhere (except the screen). This will be captured in the log file once that is solved, but perhaps it would be useful to generate a file that outputs this info for all the successful vcf's created? 

Also, on at least one sample I have received an ERROR for this walker. (It may be happening on all, but without a log file I cannot be sure.) The error message is as follows:

**Comment by tatumdmortimer** [comment]
depth of coverage not run anymore
